name: json_serializable_hivelist
description: Adding support for HiveList for json_serializable
version: 0.0.1
homepage: https://github.com/thenextappnl/json_serializable_hivelist

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.15.4

dependencies:
  json_serializable: ^4.0.2
  json_annotation: ^4.0.0
  json_serializable_type_helper_utils: ^2.0.0-nullsafety.1
  build_runner: ^1.11.5
  source_gen: ^0.9.10+3
  analyzer: ^1.1.0
  build: ^1.6.3
  hive: ^2.0.0
